version: '2'
services:
  server:
    image: tomcat:8.5
    depends_on:
     - mongodb
     - redis
    links:
     - mongodb
     - redis
    ports:
     - "8888:8080"
    volumes:
     - "../mam/warfile:/usr/local/tomcat/webapps"
#    networks:
#        mam_network:
#            ipv4_address: 128.0.0.2
  mongodb:
    image: mongo
    ports:
     - "27017:27017"
    volumes:
     - "../data/db:/data/db"
     - "../scripts:/home"
#    networks:
#        mam_network:
#            ipv4_address: 128.0.0.3

  redis:
    image: redis:2
    volumes:
      - "../data/redis:/data"
#    networks:
#        mam_network:
#            ipv4_address: 128.0.0.4

#  mysql:
#    image: mysql:5.6
#    volumes:
#        - ./data/mysql:/var/lib/mysql
#        - /home/edu/Documents/Garlan:/home
#    ports:
#        - "3306:3306"
#    environment:
#        MYSQL_DATABASE: google_ngrams
#        MYSQL_USER: root
#        MYSQL_PASSWORD: password
#        MYSQL_ROOT_PASSWORD: password
#    networks:
#        mam_network:
#            ipv4_address: 128.0.0.52
networks:
    mam_network:
      ipam:
        driver: default
        config:
          - subnet: 128.0.0.0/16
